name: gev-nn

channels:
  - conda-forge
  - pytorch
  - defaults

dependencies:
  - python=3.10
  - numpy
  - pandas
  - matplotlib
  - scipy
  - scikit-learn
  - geopandas
  - pykrige
  - pytorch
  - pip