"""Plot the selected GP models' out-of-fold parameter predictions.

The input contains exactly one geographically held-out prediction for every
TCCIP grid cell and GEV response.  These figures must not be described as
full-data fitted surfaces because each value was generated by a model that
excluded the corresponding spatial fold (and its buffer) from training.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from project_paths import PROCESSED_DATA_DIR, TABLE_DIR


TARGET_LABELS = {
    "mu": r"$\hat{\mu}$",
    "log_sigma": r"$\widehat{\log\sigma}$",
    "xi": r"$\hat{\xi}$",
}


def load_selected_oof(
    prediction_path: str | Path,
    location_path: str | Path,
) -> pd.DataFrame:
    """Load OOF predictions and attach projected GRID coordinates."""
    predictions = pd.read_csv(prediction_path)
    locations = pd.read_csv(location_path, usecols=["station", "x_km", "y_km"])
    if locations["station"].duplicated().any():
        raise ValueError("Location table contains duplicated station identifiers.")
    data = predictions.merge(
        locations,
        on="station",
        how="left",
        validate="many_to_one",
    )
    required = {"target", "station", "fold", "y_true", "y_pred", "residual", "x_km", "y_km"}
    missing = required.difference(data.columns)
    if missing:
        raise ValueError(f"OOF table is missing required columns: {sorted(missing)}")
    if data[["x_km", "y_km"]].isna().any().any():
        raise ValueError("Some OOF predictions could not be matched to GRID coordinates.")
    counts = data.groupby("target")["station"].nunique()
    if set(counts.index) != set(TARGET_LABELS) or counts.nunique() != 1:
        raise ValueError(f"Unexpected target/GRID counts: {counts.to_dict()}")
    return data


def _map(
    axis: plt.Axes,
    data: pd.DataFrame,
    value: str,
    title: str,
    cmap: str,
    vmin: float | None = None,
    vmax: float | None = None,
):
    points = axis.scatter(
        data["x_km"],
        data["y_km"],
        c=data[value],
        s=13,
        marker="s",
        linewidths=0,
        cmap=cmap,
        vmin=vmin,
        vmax=vmax,
    )
    axis.set_title(title, fontsize=11)
    axis.set_aspect("equal", adjustable="box")
    axis.set_xlabel("Easting (km)")
    axis.set_ylabel("Northing (km)")
    axis.grid(alpha=0.15, linewidth=0.5)
    plt.colorbar(points, ax=axis, shrink=0.78, pad=0.02)


def plot_oof_prediction_surfaces(data: pd.DataFrame) -> plt.Figure:
    """Create a concise one-row map of the three selected OOF predictions."""
    figure, axes = plt.subplots(1, 3, figsize=(13.5, 5.5), constrained_layout=True)
    for axis, target in zip(axes, TARGET_LABELS):
        part = data.loc[data["target"].eq(target)].copy()
        _map(
            axis,
            part,
            "y_pred",
            f"{TARGET_LABELS[target]} OOF prediction",
            "viridis",
        )
    figure.suptitle(
        "Selected GP models: geographically out-of-fold parameter surfaces",
        fontsize=14,
    )
    return figure


def plot_oof_residual_surfaces(
    data: pd.DataFrame,
    selected_models: pd.DataFrame | None = None,
) -> plt.Figure:
    """Create a one-row map of OOF residuals for the latest selected models."""
    figure, axes = plt.subplots(1, 3, figsize=(13.5, 5.5), constrained_layout=True)
    for axis, target in zip(axes, TARGET_LABELS):
        part = data.loc[data["target"].eq(target)].copy()
        residual_limit = float(np.nanquantile(np.abs(part["residual"]), 0.99))
        model_description = ""
        if selected_models is not None:
            model = selected_models.loc[selected_models["target"].eq(target)].iloc[0]
            predictors = str(model["predictors"]).replace("_m", "").replace("_ratio", " ratio")
            kernel = str(model["kernel"])
            if kernel == "Matern" and pd.notna(model.get("nu")):
                kernel = f"Matérn nu={float(model['nu']):g}"
            model_description = f"\n{kernel}; {predictors.replace('+', ' + ')}"
        _map(
            axis,
            part,
            "residual",
            f"{TARGET_LABELS[target]} OOF residual{model_description}",
            "coolwarm",
            -residual_limit,
            residual_limit,
        )
    figure.suptitle(
        "Selected GP models: out-of-fold residual maps",
        fontsize=14,
    )
    figure.text(
        0.5,
        -0.015,
        "Residual = NN-derived reference - geographically out-of-fold GP prediction",
        ha="center",
        fontsize=10,
    )
    return figure


def plot_oof_truth_prediction_residual(data: pd.DataFrame) -> plt.Figure:
    """Compare NN-derived references, OOF predictions, and OOF residuals."""
    figure, axes = plt.subplots(3, 3, figsize=(12.5, 14), constrained_layout=True)
    for row, target in enumerate(TARGET_LABELS):
        part = data.loc[data["target"].eq(target)].copy()
        joint = np.concatenate(
            [part["y_true"].to_numpy(float), part["y_pred"].to_numpy(float)]
        )
        lower, upper = np.nanquantile(joint, [0.01, 0.99])
        residual_limit = float(np.nanquantile(np.abs(part["residual"]), 0.99))
        _map(
            axes[row, 0],
            part,
            "y_true",
            f"{TARGET_LABELS[target]} NN-derived reference",
            "viridis",
            lower,
            upper,
        )
        _map(
            axes[row, 1],
            part,
            "y_pred",
            f"{TARGET_LABELS[target]} OOF prediction",
            "viridis",
            lower,
            upper,
        )
        _map(
            axes[row, 2],
            part,
            "residual",
            f"{TARGET_LABELS[target]} OOF residual (reference - prediction)",
            "coolwarm",
            -residual_limit,
            residual_limit,
        )
    figure.suptitle(
        "Selected GP models: reference, out-of-fold prediction, and residual",
        fontsize=14,
    )
    return figure


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--prediction-path",
        type=Path,
        default=TABLE_DIR / "spatial_ffs_selected_oof_predictions.csv",
    )
    parser.add_argument(
        "--location-path",
        type=Path,
        default=PROCESSED_DATA_DIR / "grid_station_gev_params_with_loc.csv",
    )
    parser.add_argument(
        "--selected-model-path",
        type=Path,
        default=TABLE_DIR / "spatial_ffs_selected_models.csv",
    )
    parser.add_argument("--output-directory", type=Path, required=True)
    args = parser.parse_args()

    args.output_directory.mkdir(parents=True, exist_ok=True)
    data = load_selected_oof(args.prediction_path, args.location_path)
    selected_models = pd.read_csv(args.selected_model_path)

    figures = {
        "selected_gp_oof_parameter_surfaces.png": plot_oof_prediction_surfaces(data),
        "latest_multi_predictor_gp_oof_residual_maps_1x3.png": (
            plot_oof_residual_surfaces(data, selected_models)
        ),
        "selected_gp_oof_reference_prediction_residual.png": (
            plot_oof_truth_prediction_residual(data)
        ),
    }
    for filename, figure in figures.items():
        output_path = args.output_directory / filename
        figure.savefig(output_path, dpi=300, bbox_inches="tight", facecolor="white")
        plt.close(figure)
        print(output_path)


if __name__ == "__main__":
    main()
